baseURL = 'http://plagueho.github.io/'
languageCode = 'en-us'
title = 'Code and go Seek'
theme = "ananke"

disqusShortname = 'danscottraynsford'   # use disqus comments

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'dscottraynsford'               # twitter.com/YOUR_TWITTER_ID
  github = 'PlagueHO'                 # github.com/YOUR_GITHUB_ID
  rss = true                                # show rss icon

  # home page profile
  avatar = 'dscottraynsford@outlook.com'                 # gravatar email or image url
  name = 'Daniel Scott-Raynsford'
  bio = 'Partner Technology Strategist @ Microsoft. Ex. Microsoft MVP.'


  # misc
  disableHLJS = true                        # disable highlight.js
  monoDarkIcon = true                       # show monochrome dark mode icon
