name: Blog Post or Site Change
description: Propose a new blog post or suggest a change to the site
title: "[Blog/Site]: "
labels: ["blog", "site change"]
assignees: ["PlagueHO"]
body:
  - type: dropdown
    id: change_type
    attributes:
      label: What kind of change is this?
      options:
        - New Blog Post
        - Update Existing Blog Post
        - Site Feature/Design Change
        - Bug Report
        - Other
  - type: input
    id: summary
    attributes:
      label: Short Summary or Title
      description: Give a brief summary of your post or change idea.
      placeholder: e.g. "How I Used Azure OpenAI to Build a Chatbot"
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details / Description
      description: |
        Describe your idea, post, or change in detail. 
        For blog posts, outline your main points or paste your draft.
        For site changes, explain what you want to improve or fix.
      placeholder: |
        - What is this about?
        - Why is it important?
        - Any specific technologies, tools, or examples?
    validations:
      required: true
  - type: textarea
    id: tags
    attributes:
      label: Tags (for blog posts)
      description: List relevant tags (comma-separated), e.g. "Azure, AI, Python"
      placeholder: Azure, AI, Python
  - type: input
    id: publish_date
    attributes:
      label: Desired Publish Date (for blog posts)
      description: When would you like this post to go live? (optional)
      placeholder: YYYY-MM-DD
  - type: textarea
    id: images
    attributes:
      label: Images or Screenshots
      description: Paste image URLs, upload screenshots, or describe images to include.
  - type: textarea
    id: affected_pages
    attributes:
      label: Affected Pages/Sections (for site changes)
      description: Which pages or sections are involved? (optional)
      placeholder: e.g. "Homepage, About page, Footer"
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked for duplicate issues
        - label: I have included enough detail for someone else to understand
        - label: (For posts) I have included tags and draft content
        - label: (For site changes) I have described the desired outcome
  - type: textarea
    id: extra
    attributes:
      label: Additional Context or Links
      description: Add any extra info, links, or references here.
